## These functions enable the use of an objected oriented matrix
## and (cached) matrix inverse representation.

## The "makeCacheMatrix" creates an object oriented interface to a matrix
## and its inverse.  The object is implemented as a list of functions
## to manipulate the data in the object (the matrix and its inverse.)

makeCacheMatrix <- function(x = matrix()) {
    inverse <- NULL
    set <- function(y) {
        x <<- y
        inverse <<- NULL
    }
    get <- function() x
    setinverse <- function(inv) inverse <<- inv
    getinverse <- function() inverse
    return(list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse))
}


## The "cacheSolve" function returns the "matrix inverse" of the given
## composite matrix representation list as generated by "makeCacheMatrix".

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'

    inv <- x$getinverse()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data)
    x$setinverse(inv)
    return(inv)
}

# vim: ts=8 sts=4 sw=4 et :
